const properties = [
  {
    Name: "Palm Harbour",
    Address: "2699, Green Valley, Highland Lake, FL",
    Price: 600,
    MoveInDate: "17/12/2022",
    Location: "NewYork,USA",
    Type: "House",
  },
  {
    Name: "United Fortune Real Estate ",
    Address: "2928 163rd St Flushing, NY",
    Price: 1700,
    MoveInDate: "15/12/2022",
    Location: "NewYork,USA",
    Type: "House",
  },
  {
    Name: "United Fortune Real Estate 1",
    Address: "2928 163rd St Flushing, NY",
    Price: 1750,
    MoveInDate: "15/12/2022",
    Location: "NewYork,USA",
    Type: "House",
  },
  {
    Name: "United Fortune Real Estate 2",
    Address: "2928 163rd St Flushing, NY",
    Price: 1800,
    MoveInDate: "15/12/2022",
    Location: "NewYork,USA",
    Type: "House",
  },
  {
    Name: "Metro Park Reality INC.",
    Address: "17219 32nd Ave N Flushing, NY",
    Price: 1900,
    MoveInDate: "15/12/2022",
    Location: "NewYork,USA",
    Type: "House",
  },
  {
    Name: "City House Reality INC",
    Address: "9 Bell StStaten Island, NY",
    Price: 2600,
    MoveInDate: "20/12/2022",
    Location: "NewYork,USA",
    Type: "House",
  },
  {
    Name: "Hillside Place",
    Address: "8750 167th St Jamaica, NY",
    Price: 2499,
    MoveInDate: "15/12/2022",
    Location: "NewYork,USA",
    Type: "Apartments",
  },
  {
    Name: "Park Haven Place",
    Address: "8750 167th St Jamaica, NY",
    Price: 2599,
    MoveInDate: "17/12/2022",
    Location: "NewYork,USA",
    Type: "Apartments",
  },
  {
    Name: "LosAngels",
    Address: "4000 W 22nd Pl Los Angeles, CA",
    Price: 2950,
    MoveInDate: "17/12/2022",
    Location: "LosAngels,CA",
    Type: "House",
  },
  {
    Name: "LosAngels",
    Address: "4000 W 22nd Pl Los Angeles, CA",
    Price: 2850,
    MoveInDate: "20/12/2022",
    Location: "LosAngels,CA",
    Type: "House",
  },
  {
    Name: "LosAngels 1",
    Address: "4000 W 22nd Pl Los Angeles, CA",
    Price: 2750,
    MoveInDate: "20/12/2022",
    Location: "LosAngels,CA",
    Type: "Apartments",
  },
  {
    Name: "LosAngels 2",
    Address: "4000 W 22nd Pl Los Angeles, CA",
    Price: 2650,
    MoveInDate: "27/12/2022",
    Location: "LosAngels,CA",
    Type: "Apartments",
  },
  {
    Name: "LosAngels 3",
    Address: "4000 W 22nd Pl Los Angeles, CA",
    Price: 2550,
    MoveInDate: "27/12/2022",
    Location: "LosAngels,CA",
    Type: "Apartments",
  },
  {
    Name: "Texas ",
    Address: "6331 Siers St Texas City, TX",
    Price: 1575,
    MoveInDate: "15/12/2022",
    Location: "TexasCity,TX",
    Type: "House",
  },
  {
    Name: "Texas 1",
    Address: "6331 Siers St Texas City, TX",
    Price: 1775,
    MoveInDate: "15/12/2022",
    Location: "TexasCity,TX",
    Type: "House",
  },
  {
    Name: "Texas 2",
    Address: "6331 Siers St Texas City, TX",
    Price: 1975,
    MoveInDate: "17/12/2022",
    Location: "TexasCity,TX",
    Type: "House",
  },
  {
    Name: "Texas 3",
    Address: "6331 Siers St Texas City, TX",
    Price: 2175,
    MoveInDate: "17/12/2022",
    Location: "TexasCity,TX",
    Type: "House",
  },
  {
    Name: "Texas 4",
    Address: "6331 Siers St Texas City, TX",
    Price: 2375,
    MoveInDate: "20/12/2022",
    Location: "TexasCity,TX",
    Type: "Apartments",
  },

  {
    Name: "Texas 3",
    Address: "6331 Siers St Texas City, TX",
    Price: 1275,
    MoveInDate: "27/12/2022",
    Location: "TexasCity,TX",
    Type: "Apartments",
  },
];

export default properties;
